// <auto-generated />
namespace The_Mozzarella_Fellas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Madenameandpricerequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Madenameandpricerequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201812291217270_Made name and price required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
